version: '3'

networks:
  mynet:

services:
  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../database/:/docker-entrypoint-initdb.d/
    networks:
      - mynet

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - database
    volumes:
      - ../app:/var/www
    networks:
      - mynet

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    networks:
      - mynet